#!/usr/bin/env python3
"""Build the blind context-coding prompts for the nefesh study.

Reads verse files (one verse per line) from פסוקים-לפי-סטרונג/, samples the
control groups, adds ~10% duplicates for a consistency check, shuffles
everything, splits it into batches and writes one full prompt per batch
(from verses-analysis-prompt.template.md), plus a manifest for the analysis.

Deterministic: rerunning with the same SEED gives the same output.
"""
import collections
import csv
import random
import re
import shutil
from pathlib import Path

SEED = 20260925
BATCH_SIZE = 25
DUP_RATE = 0.10

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
SRC = HERE / "פסוקים-לפי-סטרונג"
TEMPLATE = HERE / "verses-analysis-prompt.template.md"
OUT = HERE / "פרומפטים-לניתוח-פסוקים"
RESULTS = HERE / "תוצאות-ניתוח-פסוקים"
RESULTS_REL = RESULTS.relative_to(REPO)
RUNNER = HERE / "execute-verses-analysis-sessions.sh"

# (group name, [(file, lemma)], sample size or None for all, optional word filter)
CHAYIM = re.compile(r"^[ובלמכה]*חיי(ם|ך|ו|כם|הם|נו|כי|ה|ן)?$")
GROUPS = [
    ("נפש", [("H5314 - נפש - פועל.txt", "נפש"), ("H5315 - נפש - שם עצם.txt", "נפש")], None, None),
    ("איש-אשה", [("H376 - איש - שם עצם.txt", "איש"), ("H802 - אשה - שם עצם.txt", "אשה")], 150, None),
    ("אדם", [("H120 - אדם - שם עצם.txt", "אדם")], 150, None),
    ("לב-לבב", [("H3820 - לב - שם עצם.txt", "לב"), ("H3824 - לבב - שם עצם.txt", "לבב")], 150, None),
    ("חיים", [("H2416 - חי - שם עצם.txt", "חיים")], 150, CHAYIM),
    ("רוח", [("H7307 - רוח - שם עצם.txt", "רוח")], 100, None),
    ("חיה-פועל", [("H2421 - חיה - פועל.txt", "חיה")], 75, None),
]

CATEGORIES = [
    ("סכנה לחיים / הצלה / המתה",
     "a threat to life, pursuit to kill, killing, or rescue, escape or ransom from death."),
    ("צורך גופני / רעב / צמא / שובע / תיאבון",
     "bodily need or its satisfaction: hunger, thirst, eating, drinking, satiety, appetite, craving (including figurative uses clearly built on these)."),
    ("התאוששות / מנוחה / ויסות",
     "recovery, rest, refreshment, calming, or return to balance after exertion or distress."),
    ("תלות: חיים בידי אחר",
     "lives that depend on someone else: being responsible for, owning, feeding, holding captive, buying, selling or controlling people; life being 'in someone's hand'."),
    ("דחייה / גועל / מיאוס",
     "aversion: disgust, loathing, rejection, being fed up with something."),
    ("עולם המתים",
     "the realm of the dead: a corpse, a grave, impurity from contact with the dead, Sheol, the dead as such (the act of dying or killing belongs to 'סכנה לחיים / הצלה / המתה')."),
    ("רגש / יחסים / אהבה",
     "emotion or relationship: love, grief, joy, bitterness, longing, attachment between persons, an inner emotional state."),
    ("חוק / פולחן / טהרה",
     "law, cult or purity: a legal rule or commandment, sin and its consequence, sacrifice, vow, oath, purity rules."),
    ("ספירה / זהות / אזכור של אדם",
     "counting, identity or plain reference to a person: enumeration, census, lists, 'someone / anyone', designating a person or group."),
]
OTHER = ("אחר", "none of the categories above fits the target word's context.")

NIQQUD = re.compile(r"[֑-ׇ]")
LINE = re.compile(r"^`([^`]+)`\s*\(([^()]+)\)\s*$")


def strip(text):
    return NIQQUD.sub("", text)


def load(fname):
    verses = []
    for raw in (SRC / fname).read_text(encoding="utf-8").splitlines():
        if not raw.strip():
            continue
        m = LINE.match(raw.strip())
        if not m:
            raise ValueError(f"unexpected line in {fname}: {raw}")
        verses.append((m.group(2), raw.strip(), m.group(1)))
    return verses


RUNNER_HEAD = r"""#!/usr/bin/env bash
# Runs one Claude Code session per prompt file (generated by build-verses-analysis-prompts.py).
# Each session writes <N>.partial.txt and renames it to <N>.txt when done.
# Rerunnable: batches whose <N>.txt already exists are skipped.
set -u

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
PROMPTS="misc/פנייה לבלשנים/פרומפטים-לניתוח-פסוקים"
RESULTS="misc/פנייה לבלשנים/תוצאות-ניתוח-פסוקים"
LOGS="misc/פנייה לבלשנים/לוגים-ניתוח-פסוקים"
TIMEOUT_SECONDS=900

cd "$REPO" || exit 1
mkdir -p "$RESULTS" "$LOGS"

run_prompt() {
  local n="$1"
  local prompt="$PROMPTS/$n.md"
  local final="$RESULTS/$n.txt"
  local partial="$RESULTS/$n.partial.txt"

  if [ -f "$final" ]; then
    echo "[$n] already done - skipping"
    return 0
  fi
  rm -f "$partial"
  echo "[$n] $(date '+%H:%M:%S') starting"

  claude -p "$(cat "$prompt")" \
    --model opus \
    --effort medium \
    --permission-mode acceptEdits \
    --allowedTools "Read" "Write" "Bash(mv:*)" \
    > "$LOGS/$n.log" 2>&1

  local waited=0
  while [ ! -f "$final" ] || [ -f "$partial" ]; do
    if [ "$waited" -ge "$TIMEOUT_SECONDS" ]; then
      echo "[$n] ERROR: $final was not created (see $LOGS/$n.log)"
      return 1
    fi
    sleep 5
    waited=$((waited + 5))
  done
  echo "[$n] $(date '+%H:%M:%S') done"
}

"""


def write_runner(n_batches):
    lines = [RUNNER_HEAD] + [f"run_prompt {n}" for n in range(1, n_batches + 1)]
    RUNNER.write_text("\n".join(lines) + "\n", encoding="utf-8")
    RUNNER.chmod(0o755)


def main():
    rng = random.Random(SEED)
    used_refs = set()
    items = []  # dicts: group, target, ref, line
    report = []

    for group, files, size, word_filter in GROUPS:
        pool = collections.OrderedDict()  # ref -> (line, [lemmas])
        for fname, lemma in files:
            for ref, line, text in load(fname):
                if word_filter and not any(word_filter.match(w) for w in strip(text).split()):
                    continue
                if ref in pool:
                    pool[ref][1].append(lemma)
                else:
                    pool[ref] = (line, [lemma])
        if group != "נפש":
            for ref in list(pool):
                if ref in used_refs or "נפש" in strip(pool[ref][0]):
                    del pool[ref]
        refs = list(pool)
        chosen = refs if size is None else rng.sample(refs, min(size, len(refs)))
        for ref in chosen:
            line, lemmas = pool[ref]
            items.append({"group": group, "target": rng.choice(sorted(set(lemmas))), "ref": ref, "line": line})
            used_refs.add(ref)
        report.append(f"{group}: pool {len(refs)}, chosen {len(chosen)}")

    # duplicates for the consistency check
    n_dup = round(len(items) * DUP_RATE)
    originals = rng.sample(range(len(items)), n_dup)
    all_items = [dict(it, dup_of=None) for it in items]
    for i in originals:
        all_items.append(dict(items[i], dup_of=i))
    for idx, it in enumerate(all_items):
        it["key"] = idx

    # shuffle, then make sure no duplicate shares a batch with its original
    rng.shuffle(all_items)
    batch_of = lambda pos: pos // BATCH_SIZE
    for _ in range(10000):
        pos = {it["key"]: p for p, it in enumerate(all_items)}
        clash = [p for p, it in enumerate(all_items)
                 if it["dup_of"] is not None and batch_of(p) == batch_of(pos[it["dup_of"]])]
        if not clash:
            break
        p = clash[0]
        q = rng.randrange(len(all_items))
        all_items[p], all_items[q] = all_items[q], all_items[p]
    else:
        raise RuntimeError("could not separate duplicates from their originals")

    for new_id, it in enumerate(all_items, 1):
        it["id"] = new_id
    id_of_key = {it["key"]: it["id"] for it in all_items}

    # write prompts
    template = TEMPLATE.read_text(encoding="utf-8")
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    RESULTS.mkdir(exist_ok=True)

    batches = [all_items[i:i + BATCH_SIZE] for i in range(0, len(all_items), BATCH_SIZE)]
    orders = []
    for n, batch in enumerate(batches, 1):
        cats = CATEGORIES[:]
        rng.shuffle(cats)
        cats.append(OTHER)
        orders.append((n, [c[0] for c in cats]))
        cat_text = "\n".join(f"- **{name}**: {definition}" for name, definition in cats)
        verse_text = "\n".join(f"#{it['id']} {it['line']} [מטרה: {it['target']}]" for it in batch)
        prompt = (template
                  .replace("{{FILE_NUMBER}}", str(n))
                  .replace("{{CATEGORY_LIST}}", cat_text)
                  .replace("{{VERSES}}", verse_text)
                  .replace("{{VERSE_COUNT}}", str(len(batch)))
                  .replace("{{PARTIAL_PATH}}", f"{RESULTS_REL}/{n}.partial.txt")
                  .replace("{{FINAL_PATH}}", f"{RESULTS_REL}/{n}.txt"))
        assert "{{" not in prompt
        (OUT / f"{n}.md").write_text(prompt, encoding="utf-8")

    with open(OUT / "manifest.tsv", "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, delimiter="\t")
        w.writerow(["id", "batch", "group", "target", "ref", "duplicate_of_id", "line"])
        for n, batch in enumerate(batches, 1):
            for it in batch:
                dup = id_of_key[it["dup_of"]] if it["dup_of"] is not None else ""
                w.writerow([it["id"], n, it["group"], it["target"], it["ref"], dup, it["line"]])
    with open(OUT / "category-orders.tsv", "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, delimiter="\t")
        w.writerow(["batch"] + [f"pos{i}" for i in range(1, len(CATEGORIES) + 2)])
        for n, order in orders:
            w.writerow([n] + order)

    write_runner(len(batches))

    report.append(f"duplicates: {n_dup}")
    report.append(f"total verses: {len(all_items)}, batches: {len(batches)}")
    print("\n".join(report))


if __name__ == "__main__":
    main()
