#!/usr/bin/env bash
# Runs one Claude Code session per prompt file (generated by build-verses-analysis-prompts.py).
# Each session writes <N>.partial.txt and renames it to <N>.txt when done.
# Rerunnable: batches whose <N>.txt already exists are skipped.
set -u

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
PROMPTS="misc/פנייה לבלשנים/פרומפטים-לניתוח-פסוקים"
RESULTS="misc/פנייה לבלשנים/תוצאות-ניתוח-פסוקים"
LOGS="misc/פנייה לבלשנים/לוגים-ניתוח-פסוקים"
TIMEOUT_SECONDS=900

cd "$REPO" || exit 1
mkdir -p "$RESULTS" "$LOGS"

run_prompt() {
  local n="$1"
  local prompt="$PROMPTS/$n.md"
  local final="$RESULTS/$n.txt"
  local partial="$RESULTS/$n.partial.txt"

  echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo

  if [ -f "$final" ]; then
    echo "[$n] already done - skipping"
    return 0
  fi
  rm -f "$partial"
  echo "[$n] $(date '+%H:%M:%S') starting"

  (
    set -x
    claude -p "$(cat "$prompt")" \
      --model opus \
      --effort medium \
      --permission-mode acceptEdits \
      --allowedTools "Read" "Write" "Bash(mv:*)" 2>&1
  ) | tee "$LOGS/$n.log"

  local waited=0
  while [ ! -f "$final" ] || [ -f "$partial" ]; do
    if [ "$waited" -ge "$TIMEOUT_SECONDS" ]; then
      echo "[$n] ERROR: $final was not created (see $LOGS/$n.log)"
      return 1
    fi
    sleep 5
    waited=$((waited + 5))
  done
  echo "[$n] $(date '+%H:%M:%S') done"
}


run_prompt 1
run_prompt 2
run_prompt 3
run_prompt 4
run_prompt 5
run_prompt 6
run_prompt 7
run_prompt 8
run_prompt 9
run_prompt 10
run_prompt 11
run_prompt 12
run_prompt 13
run_prompt 14
run_prompt 15
run_prompt 16
run_prompt 17
run_prompt 18
run_prompt 19
run_prompt 20
run_prompt 21
run_prompt 22
run_prompt 23
run_prompt 24
run_prompt 25
run_prompt 26
run_prompt 27
run_prompt 28
run_prompt 29
run_prompt 30
run_prompt 31
run_prompt 32
run_prompt 33
run_prompt 34
run_prompt 35
run_prompt 36
run_prompt 37
run_prompt 38
run_prompt 39
run_prompt 40
run_prompt 41
run_prompt 42
run_prompt 43
run_prompt 44
run_prompt 45
run_prompt 46
run_prompt 47
run_prompt 48
run_prompt 49
run_prompt 50
run_prompt 51
run_prompt 52
run_prompt 53
run_prompt 54
run_prompt 55
run_prompt 56
run_prompt 57
run_prompt 58
run_prompt 59
run_prompt 60
run_prompt 61
run_prompt 62
run_prompt 63
run_prompt 64
run_prompt 65
